'\" t
.\"     Title: nvme-wdc-crash-dump
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/23/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-WDC\-CRASH\-DU" "1" "11/23/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-wdc-crash-dump \- Retrieve hgst device\*(Aqs crash dump and save to file\&.
.SH "SYNOPSIS"
.sp
.nf
\fInvme wdc crash\-dump\fR <device> [\-\-output\-file=<FILE>, \-o <FILE>]
                        [\-\-clear, \-c]
.fi
.SH "DESCRIPTION"
.sp
For the NVMe device given, sends the WDC vendor unique crash dump request and saves the result to a file\&. Crash dump for the WDC device(s) can be cleared using \-c or \-\-clear option\&.
.sp
The <device> parameter is mandatory NVMe character device (ex: /dev/nvme0)\&.
.sp
This will only work on WDC devices\&. Results for any other device are undefined\&.
.SH "OPTIONS"
.PP
\-o <FILE>, \-\-output\-file=<FILE>
.RS 4
Output file; defaults to device serial number
.RE
.PP
\-c, \-\-clear
.RS 4
Clear crash dump from device
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Gets the crash dump from the device and saves to default file:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme wdc crash\-dump /dev/nvme0
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Clears the crash dump:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme wdc crash\-dump /dev/nvme0 \-c
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Gets the crash dump from the device and saves to defined file:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme wdc crash\-dump /dev/nvme0 \-o GF1\-crash\-dump
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Clears the crash dump:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme wdc crash\-dump /dev/nvme0 \-\-clear
.fi
.if n \{\
.RE
.\}
.RE
.SH "NVME"
.sp
Part of the nvme\-user suite
