'\" t
.\"     Title: nvme-hgst-cap-diag
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/30/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-HGST\-CAP\-DIA" "1" "09/30/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-hgst-cap-diag \- Retrieve HGST device\*(Aqs diagnostic log and save to file\&.
.SH "SYNOPSIS"
.sp
.nf
\fInvme hgst cap\-diag\fR <device> [\-\-file=<FILE>, \-f <FILE>]
.fi
.SH "DESCRIPTION"
.sp
For the NVMe device given, sends the HGST Vendor Unique Capture\-Diagnostics request and saves the result to a compressed archive file\&. The NVMe device must refer to a single physical device (namespaces are not supportedi)\&. By default it will save the compressed arvhive in the current directory of the program being executed\&. In absence of pathname it will create a file with Serial Number of the given NVMe deivce\&.
.sp
This will only work on HGST devices supporting this feature\&. Results for any other device are undefined\&.
.sp
Expected status and description :\-
.TS
allbox tab(:);
ltB ltB.
T{
Status Code
T}:T{
Description
T}
.T&
lt lt
lt lt
lt lt
lt lt
lt lt.
T{
.sp
0x00
T}:T{
.sp
Purge State Idle\&.
T}
T{
.sp
0x01
T}:T{
.sp
Purge State Done\&.
T}
T{
.sp
0x02
T}:T{
.sp
Purge State Busy\&.
T}
T{
.sp
0x03
T}:T{
.sp
Purge State Error : Purge operation resulted in error, power cyale required\&.
T}
T{
.sp
0x04
T}:T{
.sp
Purge State Error : Purge operation interrupted by power cycle or reset\&.
T}
.TE
.sp 1
.sp
The <device> parameter is mandatory and may be either the NVMe character device (ex: /dev/nvme0), or a namespace block device (ex: /dev/nvme0n1)\&.
.sp
On success it returns 0, error code otherwise\&.
.SH "OPTIONS"
.PP
\-f <FILE>, \-\-file=<FILE>
.RS 4
Output file; defaults to device name provided
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Has the program issue HGST cap\-diag Vendor Unique Command without pathname:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme hgst cap\-diag /dev/nvme0
.fi
.if n \{\
.RE
.\}
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Has the program issue HGST Purge Vendor Unique Command with pathname:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme hgst cap\-diag /dev/nvme0 \-f /tmp/test
.fi
.if n \{\
.RE
.\}
.RE
.SH "NVME"
.sp
Part of the nvme HGST Vendor Unique Command suite\&.
.SH "TODO"
.sp
Review all the description before final delivery\&.
